# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cyraft application

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # Initialize submodules
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Set up Environment Variable CYPHAL_PATH
      run: |
        echo "CYPHAL_PATH=$GITHUB_WORKSPACE/demo/custom_data_types:$GITHUB_WORKSPACE/demo/public_regulated_data_types" >> $GITHUB_ENV
              
    - name: Verify CYPHAL_PATH
      run: echo $CYPHAL_PATH
      
    - name: Source and export my_env.sh
      run: |
        source $GITHUB_WORKSPACE/my_env.sh
        echo "UAVCAN__NODE__ID=$UAVCAN__NODE__ID" >> $GITHUB_ENV
        echo "UAVCAN__UDP__IFACE=$UAVCAN__UDP__IFACE" >> $GITHUB_ENV
        echo "UAVCAN__SRV__REQUEST_VOTE__ID=$UAVCAN__SRV__REQUEST_VOTE__ID" >> $GITHUB_ENV
        echo "UAVCAN__DIAGNOSTIC__SEVERITY=$UAVCAN__DIAGNOSTIC__SEVERITY" >> $GITHUB_ENV

    - name: Debug environment variables
      run: |
        echo "UAVCAN__NODE__ID=$UAVCAN__NODE__ID"
        echo "UAVCAN__UDP__IFACE=$UAVCAN__UDP__IFACE"
        echo "UAVCAN__SRV__REQUEST_VOTE__ID=$UAVCAN__SRV__REQUEST_VOTE__ID"
        echo "UAVCAN__DIAGNOSTIC__SEVERITY=$UAVCAN__DIAGNOSTIC__SEVERITY"
        
    - name: List directory for debugging
      run: ls -R $GITHUB_WORKSPACE/demo

    - name: Check DSDL directories
      run: |
        ls $GITHUB_WORKSPACE/demo/custom_data_types/sirius_cyber_corp
        ls $GITHUB_WORKSPACE/demo/public_regulated_data_types/uavcan/primitive

    - name: List directory for debugging
      run: ls -R $HOME/work/cyraft/cyraft

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
        source $GITHUB_WORKSPACE/my_env.sh
        echo "UAVCAN__NODE__ID=$UAVCAN__NODE__ID"
        echo "UAVCAN__UDP__IFACE=$UAVCAN__UDP__IFACE"
        echo "UAVCAN__SRV__REQUEST_VOTE__ID=$UAVCAN__SRV__REQUEST_VOTE__ID"
        echo "UAVCAN__DIAGNOSTIC__SEVERITY=$UAVCAN__DIAGNOSTIC__SEVERITY"
      run: pytest tests/
